version: 0.0
os: linux
files:
  - source: /
    destination: /chatapp/
hooks:
  BeforeInstall:
    - location: /chatapp/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /chatapp/scripts/start_server.sh
      timeout: 300
      runas: root

