version: 0.0
os: linux
files:
  - source: /
    destination: /chatapp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 3600
      runas: root
  AfterInstall:
    - location: scripts/req.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3600
      runas: root

 


