version: 0.0
os: linux
files:
  - source: /new_chatapp/
    destination: /chatapp/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: roo
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

