version: 0.0
os: linux
files:
  - source: /
    destination: /chatapp
hooks:
 ApplicationStop:
    - location: scripts/appstop.sh
      timeout: 3600
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3600
      runas: root

 


